routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();
Route::get('/home', function() {return view('home');
})->name('home')->middleware('auth');
Route::resource('users', \App\Http\Controllers\UserController::class)->middleware('auth');
Route::resource('obat', \App\Http\Controllers\ObatController::class)->middleware('auth');
Route::resource('distributor', \App\Http\Controllers\DistributorController::class)->middleware('auth');
Route::resource('penjualan', \App\Http\Controllers\PenjualanController::class)->middleware('auth');
Route::resource('pembelian', \App\Http\Controllers\PembelianController::class)->middleware('auth');
Route::resource('detail_penjualan', \App\Http\Controllers\DetailPenjualanController::class)->middleware('auth');
Route::resource('detail_pembelian', \App\Http\Controllers\DetailPembelianController::class)->middleware('auth');
Route::get('/exportpdf', [App\Http\Controllers\DetailPembelianController::class, 'exportpdf'])->name('exportpdf');
Route::get('/exportpdf2', [App\Http\Controllers\DetailPenjualanController::class, 'exportpdf2'])->name('exportpdf2');

app/Models/DetailPembelian.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class DetailPembelian extends Model
{
    use HasFactory;

    protected $table = 'detail_pembelian';
    protected $fillable = [
        'tgl_kadarluarsa',
        'harga_beli',
        'jumlah_beli',
        'sub_total_beli',
        'persen_margin_jual',
        'id_pembelian',
        'id_obat'
        ];

        public function fpembelian(){
            return $this->belongsTo(Pembelian::class, 'id_pembelian', 'id');
            }

        public function fobat(){
            return $this->belongsTo(Obat::class, 'id_obat', 'id');
            }
}

app/Http/Controllers/DetailPembelianController.php
<?php

namespace App\Http\Controllers;
use App\Models\DetailPembelian;
use App\Models\Pembelian;
use App\Models\Obat;
use PDF;
use Illuminate\Http\Request;

class DetailPembelianController extends Controller
{
    public function index()
    {
        $detail_pembelian = DetailPembelian::all();
        return view('detail_pembelian.index', [
        'detail_pembelian' => $detail_pembelian
        ]);
    }

public function create()
    {
    return view(
    'detail_pembelian.create', [
    'pembelian' => Pembelian::all(),
    'obat' => Obat::all()
        ]);
    }

public function store(Request $request)
    {
    $request->validate([
    'tgl_kadarluarsa' => 'required',
    'harga_beli'=> 'required',
    'jumlah_beli'=> 'required',
    'sub_total_beli'=> 'required',
    'persen_margin_jual'=> 'required',
    'id_pembelian'=> 'required',
    'id_obat'=> 'required'
    ]);
    $array = $request->only([
    'tgl_kadarluarsa',
    'harga_beli',
    'jumlah_beli',
    'sub_total_beli',
    'persen_margin_jual',
    'id_pembelian',
    'id_obat'
    ]);
    DetailPembelian::create($array);
    return redirect()->route('detail_pembelian.index')->with('success_message', 'Berhasil menambah Detail Pembelian baru');
    }

public function edit($id)
    {
    $detail_pembelian = DetailPembelian::find($id);
    if (!$detail_pembelian) return redirect()->route('detail_pembelian.index')->with('error_message', 'Detail Pembelian dengan id = '.$id.'tidak ditemukan');
    return view('detail_pembelian.edit', [
    'detail_pembelian' => $detail_pembelian,
    'pembelian' => Pembelian::all(),
    'obat' => Obat::all()
    ]);
    }

public function update(Request $request, Int $id)
    {
        $request->validate([
            'tgl_kadarluarsa' => 'required',
            'harga_beli'=> 'required',
            'jumlah_beli'=> 'required',
            'sub_total_beli'=> 'required',
            'persen_margin_jual'=> 'required',
            'id_pembelian'=> 'required',
            'id_obat'=> 'required'
            ]);
            // $detail_pembelian = DetailPembelian::find($id);

            $array = $request->only([
                'tgl_kadarluarsa',
                'harga_beli',
                'jumlah_beli',
                'sub_total_beli',
                'persen_margin_jual',
                'id_pembelian',
                'id_obat'
                ]);
            DetailPembelian::where('id', $id)->update($array);
            // $detail_pembelian->tgl_kadarluarsa = $request->tgl_kadarluarsa;
            // $detail_pembelian->harga_beli = $request->harga_beli;
            // $detail_pembelian->jumlah_beli = $request->jumlah_beli;
            // $detail_pembelian->sub_total_beli = $request->sub_total_beli;
            // $detail_pembelian->persen_margin_jual = $request->persen_margin_jual;
            // $detail_pembelian->id_pembelian = $request->id_pembelian;
            // $detail_pembelian->id_obat = $request->id_obat;
            // $detail_pembelian->save();
            return redirect()->route('detail_pembelian.index')->with('success_message', 'Berhasil mengubah Detail Pembelian');
    }

    public function destroy(string $id)
    {
        $detail_pembelian = DetailPembelian::find($id);
        if ($detail_pembelian) $detail_pembelian->delete();
        return redirect()->route('detail_pembelian.index')->with('success_message', 'Berhasil menghapus detail pembelian');
    }

    public function exportpdf(){
        $data = DetailPembelian::all();
        view()->share('data',$data);
        $pdf = PDF::loadview('detailpembelian-pdf');
        return $pdf->download('Datadetailpembelian.pdf');
    }
}

resources/views/detail_pembelian/create.blade.php
@extends('adminlte::page')
@section('title', 'Tambah Detail Pembelian')
@section('content_header')<h1 class="m-0 text-dark">Tambah Detail Pembelian</h1>
@stop
@section('content')
<form action="{{route('detail_pembelian.store')}}" method="post" enctype="multipart/form-data">
    @csrf
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">

                    <div class="form-group">
                        <label for="tgl_kadarluarsa">Tanggal Kadarluarsa</label>
                        <input type="date" class="form-control
@error('tgl_kadarluarsa') is-invalid @enderror" id="tgl_kadarluarsa" placeholder="Tanggal Kadarluarsa"
                            name="tgl_kadarluarsa" value="{{old('tgl_kadarluarsa')}}">
                        @error('tgl_kadarluarsa') <span class="textdanger">{{$message}}</span> @enderror
                    </div>
                    
                    <div class="form-group">
                        <label for="harga_beli">Harga Beli</label>
                        <input type="text" class="form-control 
@error('harga_beli') is-invalid @enderror" id="harga_beli" placeholder="Harga Beli" name="harga_beli" value="{{old('harga_beli')}}">
                        @error('harga_beli') <span class="text-danger">{{$message}}</span> @enderror
                    </div>

                    <div class="form-group">
                        <label for="jumlah_beli">Jumlah Beli</label>
                        <input type="number" class="form-control 
@error('jumlah_beli') is-invalid @enderror" id="jumlah_beli" placeholder="Jumlah Beli" name="jumlah_beli" value="{{old('jumlah_beli')}}">
                        @error('jumlah_beli') <span class="text-danger">{{$message}}</span> @enderror
                    </div>

                    <div class="form-group">
                        <label for="sub_total_beli">Sub Total Beli</label>
                        <input type="number" class="form-control 
@error('sub_total_beli') is-invalid @enderror" id="sub_total_beli" placeholder="Sub Total Beli" name="sub_total_beli" value="{{old('sub_total_beli')}}">
                        @error('sub_total_beli') <span class="text-danger">{{$message}}</span> @enderror
                    </div>

                    <div class="form-group">
                        <label for="persen_margin_jual">Persen Margin Jual</label>
                        <input type="number" class="form-control 
@error('persen_margin_jual') is-invalid @enderror" id="persen_margin_jual" placeholder="Persen Margin Jual" name="persen_margin_jual" value="{{old('persen_margin_jual')}}">
                        @error('persen_margin_jual') <span class="text-danger">{{$message}}</span> @enderror
                    </div>

                    <div class="form-group">
                        <label for="id_pembelian">No. Pembelian</label>
                        <div class="input-group">
                            <input type="hidden" name="id_pembelian" id="id_pembelian" value="{{old('id_pembelian')}}">
                            <input type="text" class="form-control
@error('nonota_beli') is-invalid @enderror" placeholder="No. Pembelian" id="nonota_beli" name="nonota_beli" value="{{old('nonota_beli')}}" arialabel="Alamat" aria-describedby="cari" readonly>
                            <button class="btn btn-warning" type="button" data-bs-toggle="modal" id="cari" data-bs-target="#staticBackdrop"></i>
                                Cari Data No. Pembelian</button>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_obat">Nama Obat</label>
                        <div class="input-group">
                            <input type="hidden" name="id_obat" id="id_obat" value="{{old('id_obat')}}">
                            <input type="text" class="form-control
@error('nama_obat') is-invalid @enderror" placeholder="Nama Obat" id="nama_obat" name="nama_obat" value="{{old('nama_obat')}}" arialabel="Email" aria-describedby="cari" readonly>
                            <button class="btn btn-warning" type="button" data-bs-toggle="modal" id="cari" data-bs-target="#staticBackdrop1"></i>
                                Cari Data Nama Obat</button>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Simpan</button>
                    <a href="{{route('pembelian.index')}}" class="btn btn-default">
                        Batal
                    </a>
                </div>
            </div>
        </div>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="staticBackdrop" data-bsbackdrop="static" data-bs-keyboard="false" tabindex="-1" arialabelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg modal-dialog-scrollable p-5">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="staticBackdropLabel">Pencarian Data No. Pembelian</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <table class="table table-hover table-bordered table-stripped" id="example1">
                        <thead>
                            <tr>
                                <th>No.</th>
                                <th>No Nota Beli</th>
                                <th>Tanggal Beli</th>
                                <th>Total Beli</th>
                                <th>Opsi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($pembelian as $key => $pembelian)
                            <tr>
                                <td>{{$key+1}}</td>
                                <td>{{$pembelian->nonota_beli}}</td>
                                <td>{{$pembelian->tgl_beli}}</td>
                                <td>{{$pembelian->total_beli}}</td>
                                <td>
                                    <button type="button" class="btn btn-primary btn-xs" 
                                        onclick="pilih('{{$pembelian->id}}', '{{$pembelian->nonota_beli}}')" data-bs-dismiss="modal">
                                        Pilih
                                    </button>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- End Modal -->
    <!-- Modal -->
    <div class="modal fade" id="staticBackdrop1" data-bsbackdrop="static" data-bs-keyboard="false" tabindex="-1" arialabelledby="staticBackdropLabel1" aria-hidden="true">
        <div class="modal-dialog modal-lg modal-dialog-scrollable p-5">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="staticBackdropLabel1">Pencarian Data Nama Obat</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <table class="table table-hover table-bordered table-stripped" id="example2">
                        <thead>
                            <tr>
                                <th>No.</th>
                                <th>Nama Obat</th>
                                <th>Merk</th>
                                <th>jenis</th>
                                <th>Opsi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($obat as $key => $obat)
                            <tr>
                                <td>{{$key+1}}</td>
                                <td>{{$obat->nama_obat}}</td>
                                <td>{{$obat->merk}}</td>
                                <td>{{$obat->jenis}}</td>
                                <td>
                                    <button type="button" class="btn btn-primary btn-xs" 
                                        onclick="pilih1('{{$obat->id}}', '{{$obat->nama_obat}}')" data-bs-dismiss="modal">
                                        Pilih
                                    </button>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- End Modal -->
    @stop
    @push('js')
    <script>
    $('#example1').DataTable({
        "responsive": true,
    });

    let idPembelian = document.getElementById('id_pembelian');
    let noNotaBeli = document.getElementById('nonota_beli');
    let hargaBeli = document.getElementById('harga_beli');
    let jumlahBeli = document.getElementById('jumlah_beli');
    let subTotalBeli = document.getElementById('sub_total_beli');
    let persenMarginJual = document.getElementById('persen_margin_jual');


    jumlahBeli.addEventListener('change', function(){
        return subTotalBeli.value = this.value*hargaBeli.value - this.value*hargaBeli.value*(persenMarginJual.value/100); 
    })

    persenMarginJual.addEventListener('change', function(){
        return subTotalBeli.value = hargaBeli.value*jumlahBeli.value - hargaBeli.value*jumlahBeli.value*(this.value/100); 
    })

    hargaBeli.addEventListener('change', function(){
        return subTotalBeli.value = this.value*jumlahBeli.value - this.value*jumlahBeli.value*(persenMarginJual.value/100); 
    })

    //Fungsi pilih untuk memilih data bidang studi dan mengirimkan data Bidang Studi dari Modal ke form tambah

    function pilih(id, pembelian) {
        idPembelian.value = id
        noNotaBeli.value = pembelian
    }


    $('#example2').DataTable({
        "responsive": true,
    });
    //Fungsi pilih untuk memilih data bidang studi dan mengirimkan data Bidang Studi dari Modal ke form tambah

    function pilih1(id, obat) {
        document.getElementById('id_obat').value = id
        document.getElementById('nama_obat').value = obat
    }
    </script>
    @endpush

resources/views/detail_pembelian/edit.blade.php
@extends('adminlte::page')
@section('title', 'Edit Detail Pembelian')
@section('content_header')
<h1 class="m-0 text-dark">Edit Detail Pembelian</h1>
@stop
@section('content')
<form action="{{route('detail_pembelian.update', $detail_pembelian)}}" method="post" enctype="multipart/form-data">
    @method('PUT')
    @csrf
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">

                    <div class="form-group">
                        <label for="tgl_kadarluarsa">Tanggal Kadarluarsa</label>
                        <input type="date" class="form-control
@error('tgl_kadarluarsa') is-invalid @enderror" id="tgl_kadarluarsa" placeholder="Tanggal Kadarluarsa"
                            name="tgl_kadarluarsa" value="{{$detail_pembelian->tgl_kadarluarsa ?? old('tgl_kadarluarsa')}}">
                        @error('tgl_kadarluarsa') <span class="textdanger">{{$message}}</span> @enderror
                    </div>

                    <div class="form-group">
                        <label for="harga_beli">Harga Beli</label>
                        <input type="text" class="form-control
@error('harga_beli') is-invalid @enderror" id="harga_beli" placeholder="Harga Beli" name="harga_beli" value="{{$detail_pembelian->harga_beli ?? old('harga_beli')}}">
                        @error('harga_beli') <span class="text-danger">{{$message}}</span> @enderror
                    </div>

                    <div class="form-group">
                        <label for="jumlah_beli">Jumlah Beli</label>
                        <input type="number" class="form-control
@error('jumlah_beli') is-invalid @enderror" id="jumlah_beli" placeholder="Jumlah Beli" name="jumlah_beli" value="{{$detail_pembelian->jumlah_beli ?? old('jumlah_beli')}}">
                        @error('jumlah_beli') <span class="text-danger">{{$message}}</span> @enderror
                    </div>

                    <div class="form-group">
                        <label for="sub_total_beli">Sub Total Beli</label>
                        <input type="number" class="form-control
@error('sub_total_beli') is-invalid @enderror" id="sub_total_beli" placeholder="Sub Total Beli" name="sub_total_beli" value="{{$detail_pembelian->sub_total_beli ?? old('sub_total_beli')}}">
                        @error('sub_total_beli') <span class="text-danger">{{$message}}</span> @enderror
                    </div>

                    <div class="form-group">
                        <label for="persen_margin_jual">Persen Margin Jual</label>
                        <input type="number" class="form-control
@error('persen_margin_jual') is-invalid @enderror" id="persen_margin_jual" placeholder="Persen Margin Jual" name="persen_margin_jual" value="{{$detail_pembelian->persen_margin_jual ?? old('persen_margin_jual')}}">
                        @error('persen_margin_jual') <span class="text-danger">{{$message}}</span> @enderror
                    </div>

                    <div class="form-group">
                        <label for="id_pembelian">No. Pembelian</label>
                        <div class="input-group">
                            <input type="hidden" name="id_pembelian" id="id_pembelian" value="{{$detail_pembelian->id_pembelian ?? old('id_pembelian')}}">
                            <input type="text" class="form-control
@error('nonota_beli') is-invalid @enderror" placeholder="No. Pembelian" id="nonota_beli" name="nonota_beli" value="{{$detail_pembelian->fpembelian->nonota_beli ?? old('nonota_beli')}}" arialabel="Alamat" aria-describedby="cari" readonly>
                            <button class="btn btn-warning" type="button" data-bs-toggle="modal" id="cari" data-bs-target="#staticBackdrop"></i>
                                Cari Data No. Penjualan</button>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_obat">Nama Obat</label>
                        <div class="input-group">
                            <input type="hidden" name="id_obat" id="id_obat" value="{{$detail_pembelian->id_obat ?? old('id_obat')}}">
                            <input type="text" class="form-control
@error('nama_obat') is-invalid @enderror" placeholder="Nama Obat" id="nama_obat" name="nama_obat" value="{{$detail_pembelian->fobat->nama_obat ?? old('nama_obat')}}" arialabel="Email" aria-describedby="cari" readonly>
                            <button class="btn btn-warning" type="button" data-bs-toggle="modal" id="cari" data-bs-target="#staticBackdrop1"></i>
                                Cari Data Nama Obat</button>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Simpan</button>
                    <a href="{{route('detail_pembelian.index')}}" class="btn btn-danger">
                        Batal
                    </a>
                </div>
            </div>
        </div>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="staticBackdrop" data-bsbackdrop="static" data-bs-keyboard="false" tabindex="-1" arialabelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg modal-dialog-scrollable p-5">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="staticBackdropLabel">Pencarian Data No. Pembelian</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <table class="table table-hover table-bordered table-stripped" id="example1">
                        <thead>
                            <tr>
                                <th>No.</th>
                                <th>No Nota Beli</th>
                                <th>Tanggal Beli</th>
                                <th>Total Beli</th>
                                <th>Opsi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($pembelian as $key => $pembelian)
                            <tr>
                                <td>{{$key+1}}</td>
                                <td>{{$pembelian->nonota_beli}}</td>
                                <td>{{$pembelian->tgl_beli}}</td>
                                <td>{{$pembelian->total_beli}}</td>
                                <td>
                                    <button type="button" class="btn btn-primary btn-xs"
                                        onclick="pilih('{{$pembelian->id}}', '{{$pembelian->nonota_beli}}')" data-bs-dismiss="modal">
                                        Pilih
                                    </button>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- End Modal -->
    <!-- Modal -->
    <div class="modal fade" id="staticBackdrop1" data-bsbackdrop="static" data-bs-keyboard="false" tabindex="-1" arialabelledby="staticBackdropLabel1" aria-hidden="true">
        <div class="modal-dialog modal-lg modal-dialog-scrollable p-5">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="staticBackdropLabel1">Pencarian Data Nama Obat</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <table class="table table-hover table-bordered table-stripped" id="example2">
                        <thead>
                            <tr>
                                <th>No.</th>
                                <th>Nama Obat</th>
                                <th>Merk</th>
                                <th>jenis</th>
                                <th>Opsi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($obat as $key => $obat)
                            <tr>
                                <td>{{$key+1}}</td>
                                <td>{{$obat->nama_obat}}</td>
                                <td>{{$obat->merk}}</td>
                                <td>{{$obat->jenis}}</td>
                                <td>
                                    <button type="button" class="btn btn-primary btn-xs"
                                        onclick="pilih1('{{$obat->id}}', '{{$obat->nama_obat}}')" data-bs-dismiss="modal">
                                        Pilih
                                    </button>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- End Modal -->
    @stop
    @push('js')
    <script>
    $('#example1').DataTable({
        "responsive": true,
    });

    let idPembelian = document.getElementById('id_pembelian');
    let noNotaBeli = document.getElementById('nonota_beli');
    let hargaBeli = document.getElementById('harga_beli');
    let jumlahBeli = document.getElementById('jumlah_beli');
    let subTotalBeli = document.getElementById('sub_total_beli');
    let persenMarginJual = document.getElementById('persen_margin_jual');


    jumlahBeli.addEventListener('change', function(){
        return subTotalBeli.value = this.value*hargaBeli.value - this.value*hargaBeli.value*(persenMarginJual.value/100); 
    })

    persenMarginJual.addEventListener('change', function(){
        return subTotalBeli.value = hargaBeli.value*jumlahBeli.value - hargaBeli.value*jumlahBeli.value*(this.value/100); 
    })

    hargaBeli.addEventListener('change', function(){
        return subTotalBeli.value = this.value*jumlahBeli.value - this.value*jumlahBeli.value*(persenMarginJual.value/100); 
    })
    //Fungsi pilih untuk memilih data bidang studi dan mengirimkan data Bidang Studi dari Modal ke form tambah

    // function pilih(id, pembelian) {
    //     document.getElementById('id_pembelian').value = id
    //     document.getElementById('nonota_beli').value = pembelian
    // }
    function pilih(id, pembelian) {
        idPembelian.value = id
        noNotaBeli.value = pembelian
    }


    $('#example2').DataTable({
        "responsive": true,
    });
    //Fungsi pilih untuk memilih data bidang studi dan mengirimkan data Bidang Studi dari Modal ke form tambah

    function pilih1(id, obat) {
        document.getElementById('id_obat').value = id
        document.getElementById('nama_obat').value = obat
    }
    </script>
    @endpush

resources/views/detail_pembelian/index.blade.php
@extends('adminlte::page')
@section('title', 'List Detail Pembelian')
@section('content_header')
<h1 class="m-0 text-dark">List Detail Pembelian</h1>
@stop
@section('content')
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
            @can('pemilik-only')
                <a href="/exportpdf" class="btn btn-info mb-2">
                Export Pdf
                </a>
                @endcan
                @can('gudang-only')
                <a href="{{route('detail_pembelian.create')}}" class="btn btn-primary mb-2">Tambah
                </a>
                @endcan
                <table class="table table-hover table-bordered table-stripped" id="example2">
                    <thead>
                        <tr>
                            <th>No.</th>
                            <th>Nama Obat</th>
                            <th>Harga Beli</th>
                            <th>Jumlah Beli</th>
                            <th>Persen Margin Jual</th>
                            <th>Sub Total Beli</th>
                            <th>No. Pembelian</th>
                            <th>Tanggal Kadaluarsa</th>
                            @can('gudang-only')<th>Opsi</th>@endcan
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($detail_pembelian as $key => $sk)
                        <tr>
                            <td>{{$key+1}}</td>
                            <td>{{$sk->fobat->nama_obat}}</td>
                            <td>{{$sk->harga_beli}}</td>
                            <td>{{$sk->jumlah_beli}}</td>
                            <td>{{$sk->persen_margin_jual}}</td>
                            <td>{{$sk->sub_total_beli}}</td>
                            <td>{{$sk->fpembelian->nonota_beli}}</td>
                            <td>{{$sk->tgl_kadarluarsa}}</td>
                            @can('gudang-only')
                            <td>
                                <a href="{{route('detail_pembelian.edit', $sk)}}" class="btn btn-primary btn-xs">
                                    Edit
                                </a>
                                <a href="{{route('detail_pembelian.destroy', $sk)}}" onclick="notificationBeforeDelete(event, this, <?php echo $key+1; ?>)" class="btn btn-danger btn-xs">
                                    Delete
                                </a>
                            </td>
                            @endcan
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@stop
@push('js')
<form action="" id="delete-form" method="post">
    @method('delete')
    @csrf
</form>
<script>
$('#example2').DataTable({
    "responsive": true,
});

function notificationBeforeDelete(event, el, dt) {
    event.preventDefault();
    if (confirm('Apakah anda yakin akan menghapus data detail pembelian ?')) {
        $("#delete-form").attr('action', $(el).attr('href'));
        $("#delete-form").submit();
    }
}
</script>
@endpush