routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();
Route::get('/home', function() {return view('home');
})->name('home')->middleware('auth');
Route::resource('users', \App\Http\Controllers\UserController::class)->middleware('auth');
Route::resource('obat', \App\Http\Controllers\ObatController::class)->middleware('auth');
Route::resource('distributor', \App\Http\Controllers\DistributorController::class)->middleware('auth');
Route::resource('penjualan', \App\Http\Controllers\PenjualanController::class)->middleware('auth');
Route::resource('pembelian', \App\Http\Controllers\PembelianController::class)->middleware('auth');
Route::resource('detail_penjualan', \App\Http\Controllers\DetailPenjualanController::class)->middleware('auth');
Route::resource('detail_pembelian', \App\Http\Controllers\DetailPembelianController::class)->middleware('auth');
Route::get('/exportpdf', [App\Http\Controllers\DetailPembelianController::class, 'exportpdf'])->name('exportpdf');
Route::get('/exportpdf2', [App\Http\Controllers\DetailPenjualanController::class, 'exportpdf2'])->name('exportpdf2');

app/Models/Penjualan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Penjualan extends Model
{
    use HasFactory;

    protected $table = 'penjualan';
    protected $fillable = [
        'nonota_jual',
        'tgl_jual',
        'total_jual',
        'id_user'
        ];

        public function fuser(){
            return $this->belongsTo(User::class, 'id_user', 'id');
            }
}

app/Http/Controllers/PenjualanController.php
<?php

namespace App\Http\Controllers;

use App\Models\Penjualan;
use App\Models\User;
use Illuminate\Http\Request;

class PenjualanController extends Controller
{
    public function index()
        {
            $penjualan = Penjualan::all();
            return view('penjualan.index', [
            'penjualan' => $penjualan
            ]);
        }

    public function create()
        { 
        return view( 
        'penjualan.create', [ 
        'users' => User::all()
            ]);
        }

    public function store(Request $request)
        { 
        $request->validate([
        'nonota_jual' => 'required', 
        'tgl_jual'=> 'required',
        'total_jual'=> 'required',
        'id_user'=> 'required'
        ]);
        $array = $request->only([
        'nonota_jual', 'tgl_jual', 'total_jual', 'id_user'
        ]);
        Penjualan::create($array);
        return redirect()->route('penjualan.index')->with('success_message', 'Berhasil menambah penjualan baru');
        }

    public function edit($id)
        {
        $penjualan = Penjualan::find($id);
        if (!$penjualan) return redirect()->route('penjualan.index')->with('error_message', 'Penjualan dengan id = '.$id.'tidak ditemukan');
        return view('penjualan.edit', [
        'penjualan' => $penjualan,
        'users' => User::all() 
        ]);
        }

    public function update(Request $request, $id)
        {
            $request->validate([
                'nonota_jual' => 'required',
                'tgl_jual' => 'required',
                'total_jual' => 'required',
                'id_user' => 'required'
                ]);
                $penjualan = Penjualan::find($id);
                $penjualan->nonota_jual = $request->nonota_jual;
                $penjualan->tgl_jual = $request->tgl_jual;
                $penjualan->total_jual = $request->total_jual;
                $penjualan->id_user = $request->id_user;
                $penjualan->save();
                return redirect()->route('penjualan.index')->with('success_message', 'Berhasil mengubah penjualan');
        }

    public function destroy(string $id)
        {
            $penjualan = Penjualan::find($id);
            if ($penjualan) $penjualan->delete();
            return redirect()->route('penjualan.index')->with('success_message', 'Berhasil menghapus penjualan');
        }
}

resources/views/penjualan/create.blade.php
@extends('adminlte::page')
@section('title', 'Tambah Penjualan')
@section('content_header')<h1 class="m-0 text-dark">Tambah Penjualan</h1>
@stop
@section('content')
<form action="{{route('penjualan.store')}}" method="post" enctype="multipart/form-data">
    @csrf
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">

                    <div class="form-group">
                        <label for="nonota_jual">No Nota Jual</label>
                        <input type="text" class="form-control
@error('nonota_jual') is-invalid @enderror" id="nonota_jual" placeholder="No Nota Jual"
                            name="nonota_jual" value="{{old('nonota_jual')}}">
                        @error('nonota_jual') <span class="textdanger">{{$message}}</span> @enderror
                    </div>
                    
                    <div class="form-group">
                        <label for="tgl_jual">Tanggal Jual</label>
                        <input type="datetime-local" class="form-control 
@error('tgl_jual') is-invalid @enderror" id="tgl_jual" placeholder="Tanggal Jual" name="tgl_jual" value="{{old('tgl_jual')}}">
                        @error('tgl_jual') <span class="text-danger">{{$message}}</span> @enderror
                    </div>

                    <div class="form-group">
                        <label for="total_jual">Total Jual</label>
                        <input type="number" class="form-control 
@error('total_jual') is-invalid @enderror" id="total_jual" placeholder="Total Jual" name="total_jual" value="{{old('total_jual')}}">
                        @error('total_jual') <span class="text-danger">{{$message}}</span> @enderror
                    </div>

                    <div class="form-group">
                        <label for="id_user">Nama User</label>
                        <div class="input-group">
                            <input type="hidden" name="id_user" id="id_user" value="{{old('id_user')}}">
                            <input type="text" class="form-control
@error('name') is-invalid @enderror" placeholder="Nama User" id="name" name="name" value="{{old('name')}}" arialabel="Email" aria-describedby="cari" readonly>
                            <button class="btn btn-warning" type="button" data-bs-toggle="modal" id="cari" data-bs-target="#staticBackdrop"></i>
                                Cari Data Nama User</button>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Simpan</button>
                    <a href="{{route('penjualan.index')}}" class="btn btn-default">
                        Batal
                    </a>
                </div>
            </div>
        </div>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="staticBackdrop" data-bsbackdrop="static" data-bs-keyboard="false" tabindex="-1" arialabelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg modal-dialog-scrollable p-5">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="staticBackdropLabel">Pencarian Data Nama User</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <table class="table table-hover table-bordered table-stripped" id="example2">
                        <thead>
                            <tr>
                                <th>No.</th>
                                <th>Name</th>
                                <th>Nama User</th>
                                <th>Email</th>
                                <th>Opsi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($users as $key => $user)
                            <tr>
                                <td>{{$key+1}}</td>
                                <td id={{$key+1}}>{{$user->name}}</td>
                                <td>{{$user->name}}</td>
                                <td>{{$user->email}}</td>
                                <td>
                                    <button type="button" class="btn btn-primary btn-xs" 
                                        onclick="pilih('{{$user->id}}', '{{$user->name}}')" data-bs-dismiss="modal">
                                        Pilih
                                    </button>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- End Modal -->
    @stop
    @push('js')
    <script>
    $('#example2').DataTable({
        "responsive": true,
    });
    //Fungsi pilih untuk memilih data bidang studi dan mengirimkan data Bidang Studi dari Modal ke form tambah

    function pilih(id, name) {
        document.getElementById('id_user').value = id
        document.getElementById('name').value = name
    }
    </script>
    @endpush

resources/views/penjualan/edit.blade.php
@extends('adminlte::page')
@section('title', 'Edit Data Penjualan')
@section('content_header')
<h1 class="m-0 text-dark">Edit Data Penjualan</h1>
@stop
@section('content')
<form action="{{route('penjualan.update', $penjualan)}}" method="post">
    @method('PUT')
    @csrf
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">

                    <div class="form-group">
                        <label for="nonota_jual">No Nota Jual</label>
                        <input type="text" class="form-control 
@error('nonota_jual') is-invalid @enderror" id="nonota_jual" placeholder="No Nota Jual" name="nonota_jual" value="{{$penjualan->nonota_jual ?? old('nonota_jual')}}">
                        @error('nonota_jual') <span class="text-danger">{{$message}}</span> @enderror
                    </div>

                    <div class="form-group">
                        <label for="tgl_jual">Tanggal Jual</label>
                        <input type="text" class="form-control 
@error('tgl_jual') is-invalid @enderror" id="tgl_jual" placeholder="Tanggal Jual" name="tgl_jual" value="{{$penjualan->tgl_jual ?? old('tgl_jual')}}">
                        @error('tgl_jual') <span class="text-danger">{{$message}}</span> @enderror
                    </div>

                    <div class="form-group">
                        <label for="total_jual">Total Jual</label>
                        <input type="text" class="form-control 
@error('total_jual') is-invalid @enderror" id="total_jual" placeholder="Total Jual" name="total_jual" value="{{$penjualan->total_jual ?? old('total_jual')}}">
                        @error('total_jual') <span class="text-danger">{{$message}}</span> @enderror
                    </div>

                    <div class="form-group">
                        <label for="id_user">Nama User</label>
                        <div class="input-group">
                            <input type="hidden" name="id_user" id="id_user" value="{{$penjualan->id_user ?? old('id_user')}}">
                            <input type="text" class="form-control
@error('name') is-invalid @enderror" placeholder="Nama User" id="name" name="name" value="{{$penjualan->fuser->name ?? old('name')}}" arialabel="Email" aria-describedby="cari" readonly>
                            <button class="btn btn-warning" type="button" data-bs-toggle="modal" id="cari" data-bs-target="#staticBackdrop"></i>
                                Cari Data Nama User</button>
                        </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Simpan</button>
                    <a href="{{route('distributor.index')}}" class="btn btn-danger">
                        Batal
                    </a>
                </div>
            </div>
        </div>
    </div>

     <!-- Modal -->
     <div class="modal fade" id="staticBackdrop" data-bsbackdrop="static" data-bs-keyboard="false" tabindex="-1" arialabelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg modal-dialog-scrollable p-5">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="staticBackdropLabel">Pencarian Data Id User</h1>
                    <button type="button" class="btn-close" data-bsdismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <table class="table table-hover table-bordered table-stripped" id="example2">
                        <thead>
                            <tr>
                                <th>No.</th>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Id User</th>
                                <th>Opsi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($users as $key => $user)
                            <tr>
                                <td>{{$key+1}}</td>
                                <td id={{$key+1}}>{{$user->name}}</td>
                                <td>{{$user->name}}</td>
                                <td>{{$user->email}}</td>
                                <td>
                                    <button type="button" class="btn btn-primary btn-xs" 
                                        onclick="pilih('{{$user->id}}', '{{$user->name}}')" data-bs-dismiss="modal">
                                        Pilih
                                    </button>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- End Modal -->
    @stop
    @push('js')
    <script>
    $('#example2').DataTable({
        "responsive": true,
    });
    //Fungsi pilih untuk memilih data bidang studi dan mengirimkan data Bidang Studi dari Modal ke form tambah

    function pilih(id, name) {
        document.getElementById('id_user').value = id
        document.getElementById('name').value = name
    }
    </script>
    @endpush

resources/views/penjualan/index.blade.php
@extends('adminlte::page')
@section('title', 'List Penjualan')
@section('content_header')
<h1 class="m-0 text-dark">List Penjualan</h1>
@stop
@section('content')
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <a href="{{route('penjualan.create')}}" class="btn btn-primary mb-2">Tambah
                </a>
                <table class="table table-hover table-bordered table-stripped" id="example2">
                    <thead>
                        <tr>
                            <th>No.</th>
                            <th>No Nota Jual</th>
                            <th>Tanggal Jual</th>
                            <th>Total Jual</th>
                            <th>Nama User</th>
                            <th>Opsi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($penjualan as $key => $sk)
                        <tr>
                            <td>{{$key+1}}</td>
                            <td>{{$sk->nonota_jual}}</td>
                            <td>{{$sk->tgl_jual}}</td>
                            <td>{{$sk->total_jual}}</td>
                            <td id={{$key+1}}>{{$sk->fuser->name}}</td>
                            <td>
                                <a href="{{route('penjualan.edit', $sk)}}" class="btn btn-primary btn-xs">
                                    Edit
                                </a>
                                <a href="{{route('penjualan.destroy', $sk)}}" onclick="notificationBeforeDelete(event, this, <?php echo $key+1; ?>)" class="btn btn-danger btn-xs">
                                    Delete
                                </a>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@stop
@push('js')
<form action="" id="delete-form" method="post">
    @method('delete')
    @csrf
</form>
<script>
$('#example2').DataTable({
    "responsive": true,
    
});

function notificationBeforeDelete(event, el, dt) {
    event.preventDefault();
    if (confirm('Apakah anda yakin akan menghapus data Penjualan \"' + document.getElementById(dt).innerHTML + '\" ?')) {
        $("#delete-form").attr('action', $(el).attr('href'));
        $("#delete-form").submit();
    }
}
</script>
@endpush