routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();
Route::get('/home', function() {return view('home');
})->name('home')->middleware('auth');
Route::resource('users', \App\Http\Controllers\UserController::class)->middleware('auth');
Route::resource('obat', \App\Http\Controllers\ObatController::class)->middleware('auth');
Route::resource('distributor', \App\Http\Controllers\DistributorController::class)->middleware('auth');
Route::resource('penjualan', \App\Http\Controllers\PenjualanController::class)->middleware('auth');
Route::resource('pembelian', \App\Http\Controllers\PembelianController::class)->middleware('auth');
Route::resource('detail_penjualan', \App\Http\Controllers\DetailPenjualanController::class)->middleware('auth');
Route::resource('detail_pembelian', \App\Http\Controllers\DetailPembelianController::class)->middleware('auth');
Route::get('/exportpdf', [App\Http\Controllers\DetailPembelianController::class, 'exportpdf'])->name('exportpdf');
Route::get('/exportpdf2', [App\Http\Controllers\DetailPenjualanController::class, 'exportpdf2'])->name('exportpdf2');

app/Models/DetailPenjualan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class DetailPenjualan extends Model
{
    use HasFactory;

    protected $table = 'detail_penjualan';
    protected $fillable = [
        'jumlah_jual',
        'harga_jual',
        'sub_total_jual',
        'id_penjualan',
        'id_obat'
        ];

        public function fpenjualan(){
            return $this->belongsTo(Penjualan::class, 'id_penjualan', 'id');
            }

        public function fobat(){
            return $this->belongsTo(Obat::class, 'id_obat', 'id');
            }
}

app/Http/Controllers/DetailPenjualanController.php
<?php

namespace App\Http\Controllers;
use App\Models\DetailPenjualan;
use App\Models\Penjualan;
use App\Models\Obat;
use Illuminate\Http\Request;
use PDF;
class DetailPenjualanController extends Controller
{
    public function index()
    {
        $detail_penjualan = DetailPenjualan::all();
        return view('detail_penjualan.index', [
        'detail_penjualan' => $detail_penjualan
        ]);
    }

public function create()
    { 
    return view( 
    'detail_penjualan.create', [ 
    'penjualan' => Penjualan::all(),
    'obat' => Obat::all()
        ]);
    }

public function store(Request $request)
    { 
    $request->validate([
    'jumlah_jual' => 'required', 
    'harga_jual'=> 'required',
    'sub_total_jual'=> 'required',
    'id_penjualan'=> 'required',
    'id_obat'=> 'required'
    ]);
    $array = $request->only([
    'jumlah_jual', 
    'harga_jual', 
    'sub_total_jual', 
    'id_penjualan',
    'id_obat'
    ]);
    DetailPenjualan::create($array);
    return redirect()->route('detail_penjualan.index')->with('success_message', 'Berhasil menambah Detail Penjualan baru');
    }

public function edit($id)
    {
    $detail_penjualan = DetailPenjualan::find($id);
    if (!$detail_penjualan) return redirect()->route('detail_penjualan.index')->with('error_message', 'Detail Penjualan dengan id = '.$id.'tidak ditemukan');
    return view('detail_penjualan.edit', [
    'detail_penjualan' => $detail_penjualan,
    'penjualan' => Penjualan::all(),
    'obat' => Obat::all() 
    ]);
    }

public function update(Request $request, $id)
    {
        $request->validate([
            'jumlah_jual' => 'required', 
            'harga_jual'=> 'required',
            'sub_total_jual'=> 'required',
            'id_penjualan'=> 'required',
            'id_obat'=> 'required'
            ]);
            $detail_penjualan = DetailPenjualan::find($id);
            $detail_penjualan->jumlah_jual = $request->jumlah_jual;
            $detail_penjualan->harga_jual = $request->harga_jual;
            $detail_penjualan->sub_total_jual = $request->sub_total_jual;
            $detail_penjualan->id_penjualan = $request->id_penjualan;
            $detail_penjualan->id_obat = $request->id_obat;
            $detail_penjualan->save();
            return redirect()->route('detail_penjualan.index')->with('success_message', 'Berhasil mengubah Detail Penjualan');
    }

    public function destroy(string $id)
    {
        $detail_penjualan = DetailPenjualan::find($id);
        if ($detail_penjualan) $detail_penjualan->delete();
        return redirect()->route('detail_penjualan.index')->with('success_message', 'Berhasil menghapus detail penjualan');
    }

    public function exportpdf2(){
        $data = DetailPenjualan::all();
    
        view()->share('data',$data);
        $pdf = PDF::loadview('detailpenjualan-pdf');
        return $pdf->download('Datadetailpenjualan.pdf');
    }
}

resources/views/detail_penjualan/create.blade.php
@extends('adminlte::page')
@section('title', 'Tambah Detail Penjualan')
@section('content_header')<h1 class="m-0 text-dark">Tambah Detail Penjualan</h1>
@stop
@section('content')
<form action="{{route('detail_penjualan.store')}}" method="post" enctype="multipart/form-data">
    @csrf
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">

                    <div class="form-group">
                        <label for="jumlah_jual">Jumlah Jual</label>
                        <input type="text" class="form-control
@error('jumlah_jual') is-invalid @enderror" id="jumlah_jual" placeholder="Jumlah Jual"
                            name="jumlah_jual" value="{{old('jumlah_jual')}}">
                        @error('jumlah_jual') <span class="textdanger">{{$message}}</span> @enderror
                    </div>
                    
                    <div class="form-group">
                        <label for="harga_jual">Harga Jual</label>
                        <input type="text" class="form-control 
@error('harga_jual') is-invalid @enderror" id="harga_jual" placeholder="Harga Jual" name="harga_jual" value="{{old('harga_jual')}}">
                        @error('harga_jual') <span class="text-danger">{{$message}}</span> @enderror
                    </div>

                    <div class="form-group">
                        <label for="sub_total_jual">Sub Total Jual</label>
                        <input type="number" class="form-control 
@error('sub_total_jual') is-invalid @enderror" id="sub_total_jual" placeholder="Sub Total Jual" name="sub_total_jual" value="{{old('sub_total_jual')}}">
                        @error('sub_total_jual') <span class="text-danger">{{$message}}</span> @enderror
                    </div>

                    <div class="form-group">
                        <label for="id_penjualan">No. Penjualan</label>
                        <div class="input-group">
                            <input type="hidden" name="id_penjualan" id="id_penjualan" value="{{old('id_penjualan')}}">
                            <input type="text" class="form-control
@error('nonota_jual') is-invalid @enderror" placeholder="No. Penjualan" id="nonota_jual" name="nonota_jual" value="{{old('nonota_jual')}}" arialabel="Alamat" aria-describedby="cari" readonly>
                            <button class="btn btn-warning" type="button" data-bs-toggle="modal" id="cari" data-bs-target="#staticBackdrop"></i>
                                Cari Data No. Penjualan</button>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_obat">Nama Obat</label>
                        <div class="input-group">
                            <input type="hidden" name="id_obat" id="id_obat" value="{{old('id_obat')}}">
                            <input type="text" class="form-control
@error('nama_obat') is-invalid @enderror" placeholder="Nama Obat" id="nama_obat" name="nama_obat" value="{{old('nama_obat')}}" arialabel="Email" aria-describedby="cari" readonly>
                            <button class="btn btn-warning" type="button" data-bs-toggle="modal" id="cari" data-bs-target="#staticBackdrop1"></i>
                                Cari Data Nama Obat</button>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Simpan</button>
                    <a href="{{route('pembelian.index')}}" class="btn btn-default">
                        Batal
                    </a>
                </div>
            </div>
        </div>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="staticBackdrop" data-bsbackdrop="static" data-bs-keyboard="false" tabindex="-1" arialabelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg modal-dialog-scrollable p-5">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="staticBackdropLabel">Pencarian Data No. Penjualan</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <table class="table table-hover table-bordered table-stripped" id="example1">
                        <thead>
                            <tr>
                                <th>No.</th>
                                <th>No Nota Jual</th>
                                <th>Tanggal Jual</th>
                                <th>Total Jual</th>
                                <th>Opsi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($penjualan as $key => $penjualan)
                            <tr>
                                <td>{{$key+1}}</td>
                                <td>{{$penjualan->nonota_jual}}</td>
                                <td>{{$penjualan->tgl_jual}}</td>
                                <td>{{$penjualan->total_jual}}</td>
                                <td>
                                    <button type="button" class="btn btn-primary btn-xs" 
                                        onclick="pilih('{{$penjualan->id}}', '{{$penjualan->nonota_jual}}')" data-bs-dismiss="modal">
                                        Pilih
                                    </button>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- End Modal -->
    <!-- Modal -->
    <div class="modal fade" id="staticBackdrop1" data-bsbackdrop="static" data-bs-keyboard="false" tabindex="-1" arialabelledby="staticBackdropLabel1" aria-hidden="true">
        <div class="modal-dialog modal-lg modal-dialog-scrollable p-5">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="staticBackdropLabel1">Pencarian Data Nama Obat</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <table class="table table-hover table-bordered table-stripped" id="example2">
                        <thead>
                            <tr>
                                <th>No.</th>
                                <th>Nama Obat</th>
                                <th>Merk</th>
                                <th>jenis</th>
                                <th>Opsi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($obat as $key => $obat)
                            <tr>
                                <td>{{$key+1}}</td>
                                <td>{{$obat->nama_obat}}</td>
                                <td>{{$obat->merk}}</td>
                                <td>{{$obat->jenis}}</td>
                                <td>
                                    <button type="button" class="btn btn-primary btn-xs" 
                                        onclick="pilih1('{{$obat->id}}', '{{$obat->nama_obat}}')" data-bs-dismiss="modal">
                                        Pilih
                                    </button>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- End Modal -->
    @stop
    @push('js')
    <script>
    $('#example1').DataTable({
        "responsive": true,
    });
    let idPenjualan = document.getElementById('id_penjualan');
    let noNotaJual = document.getElementById('nonota_jual');
    let hargaJual = document.getElementById('harga_jual');
    let jumlahJual = document.getElementById('jumlah_jual');
    let subTotalJual = document.getElementById('sub_total_jual');


    jumlahJual.addEventListener('change', function(){
        return subTotalJual.value = this.value*hargaJual.value; 
    })

    hargaJual.addEventListener('change', function(){
        return subTotalJual.value = this.value*jumlahJual.value; 
    })

    //Fungsi pilih untuk memilih data bidang studi dan mengirimkan data Bidang Studi dari Modal ke form tambah

    function pilih(id, penjualan) {
        idPenjualan.value = id
        noNotaJual.value = penjualan
    }


    $('#example2').DataTable({
        "responsive": true,
    });
    //Fungsi pilih untuk memilih data bidang studi dan mengirimkan data Bidang Studi dari Modal ke form tambah

    function pilih1(id, obat) {
        document.getElementById('id_obat').value = id
        document.getElementById('nama_obat').value = obat
    }
    </script>
    @endpush

resources/views/detail_penjualan/edit.blade.php
@extends('adminlte::page')
@section('title', 'Edit Detail Penjualan')
@section('content_header')
<h1 class="m-0 text-dark">Edit Detail Penjualan</h1>
@stop
@section('content')
<form action="{{route('detail_penjualan.update', $detail_penjualan)}}" method="post" enctype="multipart/form-data">
    @method('PUT')
    @csrf
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">

                    <div class="form-group">
                        <label for="jumlah_jual">Jumlah Jual</label>
                        <input type="text" class="form-control
@error('jumlah_jual') is-invalid @enderror" id="jumlah_jual" placeholder="Jumlah Jual"
                            name="jumlah_jual" value="{{$detail_penjualan->jumlah_jual ?? old('jumlah_jual')}}">
                        @error('jumlah_jual') <span class="textdanger">{{$message}}</span> @enderror
                    </div>

                    <div class="form-group">
                        <label for="harga_jual">Harga Jual</label>
                        <input type="text" class="form-control
@error('harga_jual') is-invalid @enderror" id="harga_jual" placeholder="Harga Jual" name="harga_jual" value="{{$detail_penjualan->harga_jual ?? old('harga_jual')}}">
                        @error('harga_jual') <span class="text-danger">{{$message}}</span> @enderror
                    </div>

                    <div class="form-group">
                        <label for="sub_total_jual">Sub Total Jual</label>
                        <input type="number" class="form-control
@error('sub_total_jual') is-invalid @enderror" id="sub_total_jual" placeholder="Sub Total Jual" name="sub_total_jual" value="{{$detail_penjualan->sub_total_jual ?? old('sub_total_jual')}}">
                        @error('sub_total_jual') <span class="text-danger">{{$message}}</span> @enderror
                    </div>

                    <div class="form-group">
                        <label for="id_penjualan">No. Penjualan</label>
                        <div class="input-group">
                            <input type="hidden" name="id_penjualan" id="id_penjualan" value="{{$detail_penjualan->id_penjualan ?? old('id_penjualan')}}">
                            <input type="text" class="form-control
@error('nonota_jual') is-invalid @enderror" placeholder="No. Penjualan" id="nonota_jual" name="nonota_jual" value="{{$detail_penjualan->fpenjualan->nonota_jual ?? old('nonota_jual')}}" arialabel="Alamat" aria-describedby="cari" readonly>
                            <button class="btn btn-warning" type="button" data-bs-toggle="modal" id="cari" data-bs-target="#staticBackdrop"></i>
                                Cari Data No. Penjualan</button>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_obat">Nama Obat</label>
                        <div class="input-group">
                            <input type="hidden" name="id_obat" id="id_obat" value="{{$detail_penjualan->id_obat ?? old('id_obat')}}">
                            <input type="text" class="form-control
@error('nama_obat') is-invalid @enderror" placeholder="Nama Obat" id="nama_obat" name="nama_obat" value="{{$detail_penjualan->fobat->nama_obat ?? old('nama_obat')}}" arialabel="Email" aria-describedby="cari" readonly>
                            <button class="btn btn-warning" type="button" data-bs-toggle="modal" id="cari" data-bs-target="#staticBackdrop1"></i>
                                Cari Data Nama Obat</button>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Simpan</button>
                    <a href="{{route('pembelian.index')}}" class="btn btn-danger">
                        Batal
                    </a>
                </div>
            </div>
        </div>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="staticBackdrop" data-bsbackdrop="static" data-bs-keyboard="false" tabindex="-1" arialabelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg modal-dialog-scrollable p-5">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="staticBackdropLabel">Pencarian Data No. Penjualan</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <table class="table table-hover table-bordered table-stripped" id="example1">
                        <thead>
                            <tr>
                                <th>No.</th>
                                <th>No Nota Jual</th>
                                <th>Tanggal Jual</th>
                                <th>Total Jual</th>
                                <th>Opsi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($penjualan as $key => $penjualan)
                            <tr>
                                <td>{{$key+1}}</td>
                                <td>{{$penjualan->nonota_jual}}</td>
                                <td>{{$penjualan->tgl_jual}}</td>
                                <td>{{$penjualan->total_jual}}</td>
                                <td>
                                    <button type="button" class="btn btn-primary btn-xs"
                                        onclick="pilih('{{$penjualan->id}}', '{{$penjualan->nonota_jual}}')" data-bs-dismiss="modal">
                                        Pilih
                                    </button>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- End Modal -->
    <!-- Modal -->
    <div class="modal fade" id="staticBackdrop1" data-bsbackdrop="static" data-bs-keyboard="false" tabindex="-1" arialabelledby="staticBackdropLabel1" aria-hidden="true">
        <div class="modal-dialog modal-lg modal-dialog-scrollable p-5">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="staticBackdropLabel1">Pencarian Data Nama Obat</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <table class="table table-hover table-bordered table-stripped" id="example2">
                        <thead>
                            <tr>
                                <th>No.</th>
                                <th>Nama Obat</th>
                                <th>Merk</th>
                                <th>jenis</th>
                                <th>Opsi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($obat as $key => $obat)
                            <tr>
                                <td>{{$key+1}}</td>
                                <td>{{$obat->nama_obat}}</td>
                                <td>{{$obat->merk}}</td>
                                <td>{{$obat->jenis}}</td>
                                <td>
                                    <button type="button" class="btn btn-primary btn-xs"
                                        onclick="pilih1('{{$obat->id}}', '{{$obat->nama_obat}}')" data-bs-dismiss="modal">
                                        Pilih
                                    </button>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- End Modal -->
    @stop
    @push('js')
    <script>
    $('#example1').DataTable({
        "responsive": true,
    });
    //Fungsi pilih untuk memilih data bidang studi dan mengirimkan data Bidang Studi dari Modal ke form tambah

    function pilih(id, penjualan) {
        document.getElementById('id_penjualan').value = id
        document.getElementById('nonota_jual').value = penjualan
    }


    $('#example2').DataTable({
        "responsive": true,
    });
    //Fungsi pilih untuk memilih data bidang studi dan mengirimkan data Bidang Studi dari Modal ke form tambah

    function pilih1(id, obat) {
        document.getElementById('id_obat').value = id
        document.getElementById('nama_obat').value = obat
    }
    </script>
    @endpush

resources/views/detail_penjualan/index.blade.php
@extends('adminlte::page')
@section('title', 'List Detail Penjualan')
@section('content_header')
<h1 class="m-0 text-dark">List Detail Penjualan</h1>
@stop
@section('content')
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
            @can('pemilik-only')
            <a href="/exportpdf2" class="btn btn-info mb-2">
                        Export Pdf
                    </a>
                    @endcan
                @can('kasir-only')
                <a href="{{route('detail_penjualan.create')}}" class="btn btn-primary mb-2">Tambah
                </a>@endcan
                <table class="table table-hover table-bordered table-stripped" id="example2">
                    <thead>
                        <tr>
                            <th>No.</th>
                            <th>No. Penjualan</th>
                            <th>Nama Obat</th>
                            <th>Jumlah Jual</th>
                            <th>Harga Jual</th>
                            <th>Sub Total Jual</th>
                            @can('kasir-only')<th>Opsi</th>@endcan
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($detail_penjualan as $key => $sk)
                        <tr>
                            <td>{{$key+1}}</td>
                            <td>{{$sk->fpenjualan->nonota_jual}}</td>
                            <td>{{$sk->fobat->nama_obat}}</td>
                            <td>{{$sk->jumlah_jual}}</td>
                            <td>{{$sk->harga_jual}}</td>
                            <td>{{$sk->sub_total_jual}}</td>
                            @can('kasir-only')<td>
                                <a href="{{route('detail_penjualan.edit', $sk)}}" class="btn btn-primary btn-xs">
                                    Edit
                                </a>
                                <a href="{{route('detail_penjualan.destroy', $sk)}}" onclick="notificationBeforeDelete(event, this, <?php echo $key+1; ?>)" class="btn btn-danger btn-xs">
                                    Delete
                                </a>
                            </td>@endcan
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@stop
@push('js')
<form action="" id="delete-form" method="post">
    @method('delete')
    @csrf
</form>
<script>
$('#example2').DataTable({
    "responsive": true,
});

function notificationBeforeDelete(event, el, dt) {
    event.preventDefault();
    if (confirm('Apakah anda yakin akan menghapus data detail penjualan ?')) {
        $("#delete-form").attr('action', $(el).attr('href'));
        $("#delete-form").submit();
    }
}
</script>
@endpush