routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Auth::routes();
Route::get('/home', function() {return view('home');
})->name('home')->middleware('auth');
Route::resource('users', \App\Http\Controllers\UserController::class)->middleware('auth');
Route::resource('obat', \App\Http\Controllers\ObatController::class)->middleware('auth');
Route::resource('distributor', \App\Http\Controllers\DistributorController::class)->middleware('auth');
Route::resource('penjualan', \App\Http\Controllers\PenjualanController::class)->middleware('auth');
Route::resource('pembelian', \App\Http\Controllers\PembelianController::class)->middleware('auth');
Route::resource('detail_penjualan', \App\Http\Controllers\DetailPenjualanController::class)->middleware('auth');
Route::resource('detail_pembelian', \App\Http\Controllers\DetailPembelianController::class)->middleware('auth');
Route::get('/exportpdf', [App\Http\Controllers\DetailPembelianController::class, 'exportpdf'])->name('exportpdf');
Route::get('/exportpdf2', [App\Http\Controllers\DetailPenjualanController::class, 'exportpdf2'])->name('exportpdf2');

app/Models/Pembelian.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Pembelian extends Model
{
    use HasFactory;

    protected $table = 'pembelian';
    protected $fillable = [
        'nonota_beli',
        'tgl_beli',
        'total_beli',
        'id_distributor',
        'id_user'
        ];

        public function fdistributor(){
            return $this->belongsTo(Distributor::class, 'id_distributor', 'id');
            }

        public function fuser(){
            return $this->belongsTo(User::class, 'id_user', 'id');
            }
}

app/Http/Controllers/PembelianController.php
<?php

namespace App\Http\Controllers;

use App\Models\Pembelian;
use App\Models\Distributor;
use App\Models\User;
use Illuminate\Http\Request;

class PembelianController extends Controller
{
    public function index()
    {
        $pembelian = Pembelian::all();
        return view('pembelian.index', [
        'pembelian' => $pembelian
        ]);
    }

public function create()
    {
    return view(
    'pembelian.create', [
    'distributor' => Distributor::all(),
    'users' => User::all()
        ]);
    }

public function store(Request $request)
    {
    $request->validate([
    'nonota_beli' => 'required',
    'tgl_beli'=> 'required',
    'total_beli'=> 'required',
    'id_distributor'=> 'required',
    'id_user'=> 'required'
    ]);
    $array = $request->only([
    'nonota_beli',
    'tgl_beli',
    'total_beli',
    'id_distributor',
    'id_user'
    ]);
    Pembelian::create($array);
    return redirect()->route('pembelian.index')->with('success_message', 'Berhasil menambah Pembelian baru');
    }

public function edit($id)
    {
    $pembelian = Pembelian::find($id);
    if (!$pembelian) return redirect()->route('pembelian.index')->with('error_message', 'Pembelian dengan id = '.$id.'tidak ditemukan');
    return view('pembelian.edit', [
    'pembelian' => $pembelian,
    'distributor' => Distributor::all(),
    'users' => User::all()
    ]);
    }

public function update(Request $request, Int $id) // itu dikasih Int sebelum variable $id biar diubah yang string jadi Int bisa cegah sql injection juga
    {
        $request->validate([
            'nonota_beli' => 'required',
            'tgl_beli' => 'required',
            'total_beli' => 'required',
            'id_distributor' => 'required',
            'id_user' => 'required'
            ]);

            // ! Ini error bel
            // $pembelian = Pembelian::find($id);
            // $pembelian->nonota_beli = $request->nonota_beli;
            // $pembelian->tgl_beli = $request->tgl_beli;
            // $pembelian->total_beli = $request->total_beli;
            // $pembelian->id_distributor = $request->id_distributor;
            // $pembelian->id_user = $request->id_user;
            // $pembelian->save();

            // ? Bisa lebih gampang gini
            $array = $request->only([
                'nonota_beli',
                'tgl_beli',
                'total_beli',
                'id_distributor',
                'id_user'
            ]);
            Pembelian::where('id', $id)->update($array);

            return redirect()->route('pembelian.index')->with('success_message', 'Berhasil mengubah pembelian');
    }

    public function destroy(Request $request, $id)
    {
        $pembelian = Pembelian::find($id);
        if ($pembelian) $pembelian->delete();
        return redirect()->route('pembelian.index')->with('success_message', 'Berhasil menghapus pembelian');
    }
}

resources/views/pembelian/create.blade.php
@extends('adminlte::page')
@section('title', 'Tambah Pembelian')
@section('content_header')<h1 class="m-0 text-dark">Tambah Pembelian</h1>
@stop
@section('content')
<form action="{{route('pembelian.store')}}" method="post" enctype="multipart/form-data">
    @csrf
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">

                    <div class="form-group">
                        <label for="nonota_beli">No Nota Beli</label>
                        <input type="text" class="form-control
@error('nonota_beli') is-invalid @enderror" id="nonota_beli" placeholder="No Nota Beli"
                            name="nonota_beli" value="{{old('nonota_beli')}}">
                        @error('nonota_beli') <span class="textdanger">{{$message}}</span> @enderror
                    </div>
                    
                    <div class="form-group">
                        <label for="tgl_beli">Tanggal Beli</label>
                        <input type="datetime-local" class="form-control 
@error('tgl_beli') is-invalid @enderror" id="tgl_beli" placeholder="Tanggal Beli" name="tgl_beli" value="{{old('tgl_beli')}}">
                        @error('tgl_beli') <span class="text-danger">{{$message}}</span> @enderror
                    </div>

                    <div class="form-group">
                        <label for="total_beli">Total Beli</label>
                        <input type="number" class="form-control 
@error('total_beli') is-invalid @enderror" id="total_beli" placeholder="Total Beli" name="total_beli" value="{{old('total_beli')}}">
                        @error('total_beli') <span class="text-danger">{{$message}}</span> @enderror
                    </div>

                    <div class="form-group">
                        <label for="id_distributor">Nama Distributor</label>
                        <div class="input-group">
                            <input type="hidden" name="id_distributor" id="id_distributor" value="{{old('id_distributor')}}">
                            <input type="text" class="form-control
@error('nama_distributor') is-invalid @enderror" placeholder="Nama Distributor" id="nama_distributor" name="nama_distributor" value="{{old('nama_distributor')}}" arialabel="Alamat" aria-describedby="cari" readonly>
                            <button class="btn btn-warning" type="button" data-bs-toggle="modal" id="cari" data-bs-target="#staticBackdrop"></i>
                                Cari Data Nama Distributor</button>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_user">Nama User</label>
                        <div class="input-group">
                            <input type="hidden" name="id_user" id="id_user" value="{{old('id_user')}}">
                            <input type="text" class="form-control
@error('name') is-invalid @enderror" placeholder="Nama User" id="name" name="name" value="{{old('name')}}" arialabel="Email" aria-describedby="cari" readonly>
                            <button class="btn btn-warning" type="button" data-bs-toggle="modal" id="cari" data-bs-target="#staticBackdrop1"></i>
                                Cari Data Nama User</button>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Simpan</button>
                    <a href="{{route('pembelian.index')}}" class="btn btn-default">
                        Batal
                    </a>
                </div>
            </div>
        </div>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="staticBackdrop" data-bsbackdrop="static" data-bs-keyboard="false" tabindex="-1" arialabelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg modal-dialog-scrollable p-5">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="staticBackdropLabel">Pencarian Data Nama Distributor</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <table class="table table-hover table-bordered table-stripped" id="example1">
                        <thead>
                            <tr>
                                <th>No.</th>
                                <th>Nama Distributor</th>
                                <th>Alamat</th>
                                <th>Opsi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($distributor as $key => $distributor)
                            <tr>
                                <td>{{$key+1}}</td>
                                <td>{{$distributor->nama_distributor}}</td>
                                <td>{{$distributor->alamat}}</td>
                                <td>
                                    <button type="button" class="btn btn-primary btn-xs" 
                                        onclick="pilih('{{$distributor->id}}', '{{$distributor->nama_distributor}}')" data-bs-dismiss="modal">
                                        Pilih
                                    </button>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- End Modal -->
    <!-- Modal -->
    <div class="modal fade" id="staticBackdrop1" data-bsbackdrop="static" data-bs-keyboard="false" tabindex="-1" arialabelledby="staticBackdropLabel1" aria-hidden="true">
        <div class="modal-dialog modal-lg modal-dialog-scrollable p-5">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="staticBackdropLabel1">Pencarian Data Nama User</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <table class="table table-hover table-bordered table-stripped" id="example2">
                        <thead>
                            <tr>
                                <th>No.</th>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Opsi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($users as $key => $user)
                            <tr>
                                <td>{{$key+1}}</td>
                                <td>{{$user->name}}</td>
                                <td>{{$user->email}}</td>
                                <td>
                                    <button type="button" class="btn btn-primary btn-xs" 
                                        onclick="pilih1('{{$user->id}}', '{{$user->name}}')" data-bs-dismiss="modal">
                                        Pilih
                                    </button>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- End Modal -->
    @stop
    @push('js')
    <script>
    // Initialize DataTables
    $('#example1').DataTable({
        "responsive": true,
    });

    let namaDistributor = document.getElementById('nama_distributor');
    let idDistributor = document.getElementById('id_distributor');

    //Fungsi pilih untuk memilih data bidang studi dan mengirimkan data Bidang Studi dari Modal ke form tambah

    function pilih(id, distributor) {
        idDistributor.value = id
        namaDistributor.value = distributor
    }


    $('#example2').DataTable({
        "responsive": true,
    });
    //Fungsi pilih untuk memilih data bidang studi dan mengirimkan data Bidang Studi dari Modal ke form tambah

    function pilih1(id, name) {
        document.getElementById('id_user').value = id
        document.getElementById('name').value = name
    }
    </script>
    @endpush

resources/views/pembelian/edit.blade.php
@extends('adminlte::page')
@section('title', 'Edit Data Pembelian')
@section('content_header')
<h1 class="m-0 text-dark">Edit Data Pembelian</h1>
@stop
@section('content')
<form action="{{route('pembelian.update', $pembelian)}}" method="post">
    @method('PUT')
    @csrf
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">

                    <div class="form-group">
                        <label for="nonota_beli">No Nota Beli</label>
                        <input type="text" class="form-control
@error('nonota_beli') is-invalid @enderror" id="nonota_beli" placeholder="No Nota Beli"
                            name="nonota_beli" value="{{$pembelian->nonota_beli ?? old('nonota_beli')}}">
                        @error('nonota_beli') <span class="textdanger">{{$message}}</span> @enderror
                    </div>

                    <div class="form-group">
                        <label for="tgl_beli">Tanggal Beli</label>
                        <input type="datetime-local" class="form-control
@error('tgl_beli') is-invalid @enderror" id="tgl_beli" placeholder="Tanggal Beli" name="tgl_beli" value="{{$pembelian->tgl_beli ?? old('tgl_beli')}}">
                        @error('tgl_beli') <span class="text-danger">{{$message}}</span> @enderror
                    </div>

                    <div class="form-group">
                        <label for="total_beli">Total Beli</label>
                        <input type="number" class="form-control
@error('total_beli') is-invalid @enderror" id="total_beli" placeholder="Total Beli" name="total_beli" value="{{$pembelian->total_beli ?? old('total_beli')}}">
                        @error('total_beli') <span class="text-danger">{{$message}}</span> @enderror
                    </div>

                    <div class="form-group">
                        <label for="id_distributor">Nama Distributor</label>
                        <div class="input-group">
                            <input type="hidden" name="id_distributor" id="id_distributor" value="{{$pembelian->id_distributor ?? old('id_distributor')}}">
                            <input type="text" class="form-control
@error('nama_distributor') is-invalid @enderror" placeholder="ID Distributor" id="nama_distributor" name="nama_distributor" value="{{$pembelian->fdistributor->nama_distributor ?? old('nama_distributor')}}" arialabel="Alamat" aria-describedby="cari" readonly>
                            <button class="btn btn-warning" type="button" data-bs-toggle="modal" id="cari" data-bs-target="#staticBackdrop"></i>
                                Cari Data Nama Distributor</button>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_user">Nama User</label>
                        <div class="input-group">
                            <input type="hidden" name="id_user" id="id_user" value="{{$pembelian->id_user ?? old('id_user')}}">
                            <input type="text" class="form-control
@error('name') is-invalid @enderror" placeholder="Nama User" id="name" name="name" value="{{$pembelian->fuser->name ?? old('name')}}" arialabel="Email" aria-describedby="cari" readonly>
                            <button class="btn btn-warning" type="button" data-bs-toggle="modal" id="cari" data-bs-target="#staticBackdrop1"></i>
                                Cari Data Nama User</button>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Simpan</button>
                    <a href="{{route('penjualan.index')}}" class="btn btn-danger">
                        Batal
                    </a>
                </div>
            </div>
        </div>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="staticBackdrop" data-bsbackdrop="static" data-bs-keyboard="false" tabindex="-1" arialabelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg modal-dialog-scrollable p-5">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="staticBackdropLabel">Pencarian Data Id Distributor</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <table class="table table-hover table-bordered table-stripped" id="example1">
                        <thead>
                            <tr>
                                <th>No.</th>
                                <th>Nama Distributor</th>
                                <th>Alamat</th>
                                <th>Opsi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($distributor as $key => $distributor)
                            <tr>
                                <td>{{$key+1}}</td>
                                <td>{{$distributor->nama_distributor}}</td>
                                <td>{{$distributor->alamat}}</td>
                                <td>
                                    <button type="button" class="btn btn-primary btn-xs"
                                        onclick="pilih('{{$distributor->id}}', '{{$distributor->nama_distributor}}')" data-bs-dismiss="modal">
                                        Pilih
                                    </button>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- End Modal -->
    <!-- Modal -->
    <div class="modal fade" id="staticBackdrop1" data-bsbackdrop="static" data-bs-keyboard="false" tabindex="-1" arialabelledby="staticBackdropLabel1" aria-hidden="true">
        <div class="modal-dialog modal-lg modal-dialog-scrollable p-5">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="staticBackdropLabel1">Pencarian Data Nama User</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <table class="table table-hover table-bordered table-stripped" id="example2">
                        <thead>
                            <tr>
                                <th>No.</th>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Opsi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($users as $key => $user)
                            <tr>
                                <td>{{$key+1}}</td>
                                <td>{{$user->name}}</td>
                                <td>{{$user->email}}</td>
                                <td>
                                    <button type="button" class="btn btn-primary btn-xs"
                                        onclick="pilih1('{{$user->id}}', '{{$user->name}}')" data-bs-dismiss="modal">
                                        Pilih
                                    </button>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- End Modal -->
    @stop
    @push('js')
    <script>
    $('#example1').DataTable({
        "responsive": true,
    });
    //Fungsi pilih untuk memilih data bidang studi dan mengirimkan data Bidang Studi dari Modal ke form tambah

    function pilih(id, distributor) {
        document.getElementById('id_distributor').value = id
        document.getElementById('nama_distributor').value = distributor
    }


    $('#example2').DataTable({
        "responsive": true,
    });
    //Fungsi pilih untuk memilih data bidang studi dan mengirimkan data Bidang Studi dari Modal ke form tambah

    function pilih1(id, name) {
        document.getElementById('id_user').value = id
        document.getElementById('name').value = name
    }
    </script>
    @endpush

resources/views/pembelian/index.blade.php
@extends('adminlte::page')
@section('title', 'List Pembelian')
@section('content_header')
<h1 class="m-0 text-dark">List Pembelian</h1>
@stop
@section('content')
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <a href="{{route('pembelian.create')}}" class="btn btn-primary mb-2">Tambah
                </a>
                <table class="table table-hover table-bordered table-stripped" id="example2">
                    <thead>
                        <tr>
                            <th>No.</th>
                            <th>No Nota Beli</th>
                            <th>Tanggal Beli</th>
                            <th>Total Beli</th>
                            <th>Nama Distributor</th>
                            <th>Nama User</th>
                            <th>Opsi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($pembelian as $key => $sk)
                        <tr>
                            <td>{{$key+1}}</td>
                            <td>{{$sk->nonota_beli}}</td>
                            <td>{{$sk->tgl_beli}}</td>
                            <td>{{$sk->total_beli}}</td>
                            <td>{{$sk->fdistributor->nama_distributor}}</td>
                            <td>{{$sk->fuser->name}}</td>
                            <td>
                                <a href="{{route('pembelian.edit', $sk)}}" class="btn btn-primary btn-xs">
                                    Edit
                                </a>
                                <a href="{{route('pembelian.destroy', $sk)}}" onclick="notificationBeforeDelete(event, this, <?php echo $key+1; ?>)" class="btn btn-danger btn-xs">
                                    Delete
                                </a>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@stop
@push('js')
<form action="" id="delete-form" method="post">
    @method('delete')
    @csrf
</form>
<script>
$('#example2').DataTable({
    "responsive": true,
});

function notificationBeforeDelete(event, el, dt) {
    event.preventDefault();
    if (confirm('Apakah anda yakin akan menghapus data pembelian ?')) {
        $("#delete-form").attr('action', $(el).attr('href'));
        $("#delete-form").submit();
    }
}
</script>
@endpush